---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: ospcloud
    region_name: RegionOne
  register: result

- name: Delete instances
  os_server:
    name: "{{ item.name }}"
    cloud: ospcloud
    state: absent
  with_items: "{{ result.openstack_servers }}"
